export const Colors = {
  light: {
    // Core brand
    primary: '#2AABEE',
    primaryDark: '#1A96D9',
    primaryLight: '#EBF6FD',
    accent: '#54C9F0',
    // Backgrounds
    background: '#FFFFFF',
    surface: '#F4F4F5',
    surfaceElevated: '#FFFFFF',
    chatBackground: '#F0F0F0',
    // Bubbles
    myMessageBubble: '#EFFDDE',
    myMessageBubbleSelected: '#D9F7C5',
    otherMessageBubble: '#FFFFFF',
    otherMessageBubbleSelected: '#EBEBEB',
    // Text
    text: '#000000',
    textSecondary: '#707579',
    textHint: '#AAAAAA',
    textOnPrimary: '#FFFFFF',
    textCaption: '#8D8D93',
    // Borders & dividers
    border: '#E4E4E4',
    divider: '#F0F0F0',
    // Input
    inputBackground: '#F0F0F0',
    inputBorder: '#E4E4E4',
    // Status
    danger: '#E53935',
    success: '#4CAF50',
    warning: '#FF9500',
    online: '#4CAF50',
    // Badges
    unreadBadge: '#2AABEE',
    unreadBadgeMuted: '#AAAAAA',
    mentionBadge: '#E53935',
    // Header & nav
    headerBackground: '#FFFFFF',
    headerBorder: '#E4E4E4',
    tabBar: '#FFFFFF',
    tabBarActive: '#2AABEE',
    tabBarInactive: '#8D8D93',
    tabBarBorder: '#E4E4E4',
    // Stories
    storyRingViewed: '#C8C8C8',
    storyRingUnviewed: '#2AABEE',
    storyRingPremium: '#DA70D6',
    // Premium
    premiumGold: '#FFD700',
    premiumGradientStart: '#6B6BFF',
    premiumGradientEnd: '#B47AFF',
    // Overlays
    overlay: 'rgba(0,0,0,0.4)',
    overlayLight: 'rgba(0,0,0,0.08)',
    skeletonBase: '#E8E8E8',
    skeletonHighlight: '#F5F5F5',
    // Reactions
    reactionBubble: '#F0F8FF',
    reactionBubbleOwn: '#E0F7E9',
    // Call
    callBackground: '#1C2733',
    callControlBg: 'rgba(255,255,255,0.18)',
    callEndBtn: '#E53935',
  },
  dark: {
    // Core brand
    primary: '#2AABEE',
    primaryDark: '#1A96D9',
    primaryLight: '#1A2733',
    accent: '#54C9F0',
    // Backgrounds
    background: '#17212B',
    surface: '#232E3C',
    surfaceElevated: '#1E2C3A',
    chatBackground: '#0E1621',
    // Bubbles
    myMessageBubble: '#2B5278',
    myMessageBubbleSelected: '#1E3D5C',
    otherMessageBubble: '#182533',
    otherMessageBubbleSelected: '#1A2B3A',
    // Text
    text: '#F5F5F5',
    textSecondary: '#708499',
    textHint: '#5C6E82',
    textOnPrimary: '#FFFFFF',
    textCaption: '#6B7F96',
    // Borders & dividers
    border: '#1E2C3A',
    divider: '#1A2530',
    // Input
    inputBackground: '#242F3D',
    inputBorder: '#1E2C3A',
    // Status
    danger: '#FF5252',
    success: '#4CAF50',
    warning: '#FF9500',
    online: '#4CAF50',
    // Badges
    unreadBadge: '#2AABEE',
    unreadBadgeMuted: '#5C6E82',
    mentionBadge: '#FF5252',
    // Header & nav
    headerBackground: '#17212B',
    headerBorder: '#1E2C3A',
    tabBar: '#17212B',
    tabBarActive: '#2AABEE',
    tabBarInactive: '#708499',
    tabBarBorder: '#1E2C3A',
    // Stories
    storyRingViewed: '#4A5A6A',
    storyRingUnviewed: '#2AABEE',
    storyRingPremium: '#DA70D6',
    // Premium
    premiumGold: '#FFD700',
    premiumGradientStart: '#6B6BFF',
    premiumGradientEnd: '#B47AFF',
    // Overlays
    overlay: 'rgba(0,0,0,0.6)',
    overlayLight: 'rgba(0,0,0,0.2)',
    skeletonBase: '#1E2C3A',
    skeletonHighlight: '#243040',
    // Reactions
    reactionBubble: '#1E3448',
    reactionBubbleOwn: '#1A3C2A',
    // Call
    callBackground: '#0E1621',
    callControlBg: 'rgba(255,255,255,0.15)',
    callEndBtn: '#FF5252',
  },
};
