export const Colors = {
  light: {
    // Core brand
    primary: '#2AABEE',
    primaryDark: '#229ED9',
    primaryLight: '#E6F6FE',
    accent: '#FF6B35',
    // Backgrounds
    background: '#FFFFFF',
    surface: '#F4F4F5',
    surfaceElevated: '#FFFFFF',
    chatBackground: '#DCE7EF',
    // Bubbles
    myMessageBubble: '#E7F7C9',
    myMessageBubbleSelected: '#D8F0B8',
    otherMessageBubble: '#FFFFFF',
    otherMessageBubbleSelected: '#EDF4F8',
    // Text
    text: '#000000',
    textSecondary: '#8E8E93',
    textHint: '#AEAEB2',
    textOnPrimary: '#FFFFFF',
    textCaption: '#8E8E93',
    // Borders & dividers
    border: '#CDD6DD',
    divider: '#E3E8ED',
    // Input
    inputBackground: '#FFFFFF',
    inputBorder: '#CDD6DD',
    // Status
    danger: '#FF3B30',
    success: '#34C759',
    warning: '#FF9500',
    online: '#31C46C',
    // Badges
    unreadBadge: '#2AABEE',
    unreadBadgeMuted: '#AEAEB2',
    mentionBadge: '#FF3B30',
    // Header & nav
    headerBackground: '#FFFFFF',
    headerBorder: '#E3E8ED',
    tabBar: '#FFFFFF',
    tabBarActive: '#2AABEE',
    tabBarInactive: '#8E8E93',
    tabBarBorder: '#C6C6C8',
    // Stories
    storyRingViewed: '#AEAEB2',
    storyRingUnviewed: '#2AABEE',
    storyRingPremium: '#FF6B35',
    // Premium
    premiumGold: '#FF8A3D',
    premiumGradientStart: '#FF8A3D',
    premiumGradientEnd: '#FF5A2A',
    // Overlays
    overlay: 'rgba(0,0,0,0.4)',
    overlayLight: 'rgba(0,0,0,0.08)',
    skeletonBase: '#E5E5EA',
    skeletonHighlight: '#F2F2F7',
    // Reactions
    reactionBubble: '#FFE9DD',
    reactionBubbleOwn: '#D9F7C4',
    // Call
    callBackground: '#1A1A1A',
    callControlBg: 'rgba(255,255,255,0.18)',
    callEndBtn: '#FF3B30',
  },
  dark: {
    // Core brand
    primary: '#2AABEE',
    primaryDark: '#229ED9',
    primaryLight: '#153343',
    accent: '#FF8A3D',
    // Backgrounds
    background: '#0F1720',
    surface: '#17212B',
    surfaceElevated: '#1F2C38',
    chatBackground: '#0E1621',
    // Bubbles  — Telegram dark green own bubbles
    myMessageBubble: '#2B5278',
    myMessageBubbleSelected: '#24496B',
    otherMessageBubble: '#182533',
    otherMessageBubbleSelected: '#20303F',
    // Text
    text: '#FFFFFF',
    textSecondary: '#8E8E93',
    textHint: '#636366',
    textOnPrimary: '#FFFFFF',
    textCaption: '#8E8E93',
    // Borders & dividers
    border: '#253443',
    divider: '#1B2733',
    // Input
    inputBackground: '#17212B',
    inputBorder: '#253443',
    // Status
    danger: '#FF453A',
    success: '#32D74B',
    warning: '#FF9F0A',
    online: '#31C46C',
    // Badges
    unreadBadge: '#2AABEE',
    unreadBadgeMuted: '#636366',
    mentionBadge: '#FF453A',
    // Header & nav
    headerBackground: '#17212B',
    headerBorder: '#22303D',
    tabBar: '#17212B',
    tabBarActive: '#2AABEE',
    tabBarInactive: '#8E8E93',
    tabBarBorder: '#22303D',
    // Stories
    storyRingViewed: '#636366',
    storyRingUnviewed: '#2AABEE',
    storyRingPremium: '#FF8A3D',
    // Premium
    premiumGold: '#FF9A4D',
    premiumGradientStart: '#FF9A4D',
    premiumGradientEnd: '#FF6B35',
    // Overlays
    overlay: 'rgba(0,0,0,0.65)',
    overlayLight: 'rgba(0,0,0,0.25)',
    skeletonBase: '#2C2C2E',
    skeletonHighlight: '#3A3A3C',
    // Reactions
    reactionBubble: '#453222',
    reactionBubbleOwn: '#0E3A2E',
    // Call
    callBackground: '#0A0A0A',
    callControlBg: 'rgba(255,255,255,0.15)',
    callEndBtn: '#FF453A',
  },
};
